[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Md Talha Yaseen Khan <111701019@smail.iitpkd.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
